# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 02:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 15, 10, 45, 31, 621366, tzinfo=utc), verbose_name='date published'),
        ),
    ]
