# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-17 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devops', '0003_auto_20170817_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name_plural': '\u54a8\u8be2'},
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='\u95ee\u9898'),
        ),
    ]
