version: '3'
services:
 mysql:
  image: mysql
  environment:
   - MYSQL_ROOT_PASSWORD=yunwei
   - MYSQL_DATABASE=docker
   - MYSQL_USER=docker
   - MYSQL_PASSWORD=docker
  expose:
   - 3306
  ports:
   - 3306:3306
  #volumes:
  # - ./data:/var/lib/mysql

 web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
   - .:/code
  ports:
   - 8000:8000
  depends_on:
   - mysql
  links:
   - mysql
