version: '3.9'
services:
 db:
  image: mysql:5.7
  environment:
   - MYSQL_ROOT_PASSWORD=3gKU2N1^dSd82E@b
   - MYSQL_DATABASE=dj
   - MYSQL_USER=dj
   - MYSQL_PASSWORD=N8J9pFhNGAA@kYUl
   - TZ=Asia/Shanghai
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=2000 --default-time-zone='+8:00'
  expose:
   - 3306
  ports:
   - 3306:3306
  volumes:
   - ./data:/var/lib/mysql

 web:
  build: .
#  #dockerfile: 可以指定dockerfile文件，默认build是指定目录并寻找当前目录下Dockerfile文件
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
   - .:/code
  ports:
   - 8000:8000
  environment:
    - DB_NAME=dj
    - DB_USER=dj
    - DB_PASSWORD=N8J9pFhNGAA@kYUl
  depends_on:
   - db
